// SPDX-FileCopyrightText: 2026 superogira <SDRg35xx project>
// SPDX-License-Identifier: GPL-3.0-or-later

package aprs

import (
	"math"
	"math/rand"
	"strings"
	"testing"
	"time"
)

func buildTestFrame() ([]byte, string) {
	info := "!1357.33N/10033.71E>045/030RG35XX SDR /A=000250"
	body := EncodeUI("HS1ABC-7", "APRS", []string{"WIDE1-1", "WIDE2-1"}, []byte(info))
	return body, info
}

// The modulator must produce audio that OUR demodulator (and by spec,
// anyone's) turns back into the same frame: FCS, stuffing, NRZI and
// LSB-first ordering all have to line up.
func TestAFSKRoundTrip(t *testing.T) {
	body, info := buildTestFrame()
	audio := Modulate(body, 0.8, 40)

	// The device feeds the demodulator 8 kHz monitor audio: decimate
	// 6:1 (content is two tones below 2.4 kHz — no aliasing) and add
	// broadband noise at a realistic level.
	rng := rand.New(rand.NewSource(7))
	fed := make([]float64, 0, len(audio)/6)
	for i := 0; i < len(audio); i += 6 {
		fed = append(fed, audio[i]+0.12*rng.NormFloat64())
	}

	dem := NewDemodulator()
	// Feed in odd-sized blocks to exercise streaming state.
	for off := 0; off < len(fed); off += 511 {
		end := off + 511
		if end > len(fed) {
			end = len(fed)
		}
		dem.Feed(fed[off:end])
	}
	frames := dem.TakeFrames()
	if len(frames) == 0 {
		t.Fatal("no frames demodulated")
	}
	var got *Frame
	for _, f := range frames {
		if fr := DecodeFrame(f); fr != nil && fr.Src == "HS1ABC-7" {
			got = fr
		}
	}
	if got == nil {
		t.Fatalf("%d frames but none from HS1ABC-7", len(frames))
	}
	if string(got.Dest) != "APRS" {
		t.Errorf("dest = %q", got.Dest)
	}
	if len(got.Digis) != 2 || got.Digis[0] != "WIDE1-1" || got.Digis[1] != "WIDE2-1" {
		t.Errorf("digis = %v", got.Digis)
	}
	if string(got.Info) != info {
		t.Errorf("info round trip:\n got %q\nwant %q", got.Info, info)
	}
}

func TestCRCMagicResidue(t *testing.T) {
	body, _ := buildTestFrame()
	lo, hi := FCSBytes(body)
	all := append(append([]byte(nil), body...), lo, hi)
	if !ValidFCS(all) {
		t.Fatal("frame with appended FCS must satisfy the magic residue")
	}
	all[len(all)-1] ^= 1
	if ValidFCS(all) {
		t.Fatal("corrupted frame must fail")
	}
}

func TestPositionUncompressed(t *testing.T) {
	// Parse a real-world style report.
	p, ok := ParsePosition([]byte("!1357.33N/10033.71E>045/030hello /A=000250"))
	if !ok {
		t.Fatal("parse failed")
	}
	if math.Abs(p.Lat-(13+57.33/60)) > 0.001 {
		t.Errorf("lat = %v", p.Lat)
	}
	if math.Abs(p.Lon-(100+33.71/60)) > 0.001 {
		t.Errorf("lon = %v", p.Lon)
	}
	if p.Table != '/' || p.Sym != '>' {
		t.Errorf("symbol %c%c", p.Table, p.Sym)
	}
	if !p.HasCS || p.CourseDeg != 45 || p.SpeedKt != 30 {
		t.Errorf("cs = %v/%v has=%v", p.CourseDeg, p.SpeedKt, p.HasCS)
	}
	if !p.HasAlt || p.AltFt != 250 {
		t.Errorf("alt = %v has=%v", p.AltFt, p.HasAlt)
	}
}

func TestPositionCompressed(t *testing.T) {
	// Compressed form of the same point, generated by base91-encoding.
	enc91 := func(v float64) string {
		n := int64(v)
		var s [5]byte
		for i := 4; i >= 0; i-- {
			s[i] = byte(33 + n%91)
			n /= 91
		}
		return string(s[:])
	}
	lat := 13.95917
	lon := 100.56183
	lat91 := enc91((90 - lat) / 90 * 380926)
	lon91 := enc91((lon + 180) / 360 * 380926)
	info := "!" + "/" + lat91 + lon91 + "["
	p, ok := ParsePosition([]byte(info))
	if !ok {
		t.Fatalf("compressed parse failed: %q", info)
	}
	if math.Abs(p.Lat-lat) > 0.001 || math.Abs(p.Lon-lon) > 0.001 {
		t.Errorf("compressed = %v,%v want %v,%v", p.Lat, p.Lon, lat, lon)
	}
}

func TestFormatPosition(t *testing.T) {
	in := "!1357.33N/10033.71E> ทดสอบ"
	out := FormatPosition(Position{Lat: 13.9555, Lon: 100.5625, Table: '/', Sym: '>'}, "ทดสอบ")
	// Round the formatted body back through the parser.
	p, ok := ParsePosition([]byte("=" + out))
	if !ok {
		t.Fatalf("own format did not parse: %q", out)
	}
	if math.Abs(p.Lat-13.9555) > 0.0002 || math.Abs(p.Lon-100.5625) > 0.0002 {
		t.Errorf("round trip drift: %v,%v", p.Lat, p.Lon)
	}
	if !strings.Contains(in, "ทดสอบ") {
		t.Fatal("sanity")
	}
	if !strings.Contains(out, "ทดสอบ") {
		t.Errorf("comment lost: %q", out)
	}
}

func TestStoreAndBeacon(t *testing.T) {
	s := NewStore()
	body, _ := buildTestFrame()
	st := s.ProcessFrame(body)
	if st == nil {
		t.Fatal("station not stored")
	}
	if st.Call != "HS1ABC-7" || s.Count() != 1 {
		t.Errorf("st=%+v count=%d", st, s.Count())
	}
	// Beacon cadence: parked cars beacon slowly, moving fast.
	if BeaconInterval(0, 60, 1800) != 1800 {
		t.Error("stationary should use the slow rate")
	}
	if BeaconInterval(60, 60, 1800) != 60 {
		t.Error("fast should use the fast rate")
	}
	mid := BeaconInterval(26, 60, 1800)
	if mid < 200 || mid > 1500 {
		t.Errorf("mid speed rate = %d", mid)
	}
	if !TurnBeaconDue(120, 30, 10, 60*time.Second, 20) {
		t.Error("110-degree turn at 30 kt should trigger a corner beacon")
	}
	if TurnBeaconDue(15, 30, 10, 60*time.Second, 20) {
		t.Error("5-degree wiggle must not trigger")
	}
}
